# Generated by Django 6.0.6 on 2026-07-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Бизнес', 'Бизнес'), ('Личное', 'Личное'), ('Налог', 'Налог')])),
                ('type', models.CharField(choices=[('Пополнение', 'Пополнение'), ('Списание', 'Списание')])),
                ('summa', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
