# Generated by Django 6.0.4 on 2026-05-04 12:14

import django.core.validators
import django.db.models.deletion
import proxy_api.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxy_api', '0001_create_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('protocol', models.CharField(validators=[proxy_api.validators.protocol_validator])),
                ('is_active', models.BooleanField(default=True)),
                ('last_user_at', models.DateTimeField(auto_now=True, null=True)),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proxy_service"."virtual_machine',
                'unique_together': {('host', 'port', 'protocol')},
            },
        ),
    ]
