# Generated by Django 6.0.4 on 2026-05-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='last_used_at',
            field=models.DateTimeField(null=True),
        ),
    ]
