# Generated by Django 6.0.4 on 2026-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0003_alter_virtualmachine_last_used_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
